### ISSUE TITLE
v1.0 版本代码？

### ISSUE THREAD

**Issue by fingerx** [kleinlee/MiniMates#5]
没有看到对应的代码，是稍后更新吗？谢谢

**Comment by kleinlee** [comment]
开源的算法部分会一直保持同步，cpp_project提供部分基础工程代码，不会一直更新。 简单来说，MiniMates作为图片数字人算法部分会一直开源并同步。 MiniMates软件作为算法的直接应用尝试，有其固定的场景、受众，会致力于优化细节体验，不会一直同步源代码。
